version: "1"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - 8000:8000
    environment:
      API_PORT: ${API_PORT}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DBNAME: ${PG_DBNAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      SHORTENER_URL: ${SHORTENER_URL}
      GETTER_URL: ${GETTER_URL}

  getter:
    build: ./getter
    ports:
      - 5002:5002
    environment:
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DBNAME: ${PG_DBNAME}

  shortener:
    build: ./shortener_server
    ports:
      - 5001:5001
    environment:
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DBNAME: ${PG_DBNAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
